<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class CityFactory extends Factory
{
    // List of Moroccan cities
    protected $moroccanCities = [
        "Casablanca",
        "Rabat",
        "Marrakech",
        "Fes",
        "Tangier",
        "Agadir",
        "Meknes",
        "Oujda",
        "Kenitra",
        "Tetouan",
        "Safi",
        "Mohammedia",
        "El Jadida",
        "Beni Mellal",
        "Taza",
        "Nador",
        "Settat",
        "Khouribga",
        "Ouarzazate",
        "Berkane",
        "Larache",
        "Ksar El Kebir",
        "Essaouira",
        "Al Hoceima",
        "Taroudant",
        "Errachidia",
        "Guelmim",
        "Tiznit",
        "Laghouat",
        "Ouezzane",
        "Laayoune",
        "Boujdour",
        "Skhirat",
        "Bouznika",
        "Temara",
        "Sidi Kacem",
        "Tiflet",
        "Dakhla",
        "Martil",
        "Sidi Slimane",
        "Sefrou",
        "Midelt",
        "Chefchaouen",
        "Azrou",
        "Taourirt",
        "Oulad Teima",
        "Sidi Bennour",
        "Zagora",
        # Sub-cities and towns
        "Hay Hassani (Casablanca)",
        "Ain Chock (Casablanca)",
        "Anfa (Casablanca)",
        "Mohammed V International Airport (Casablanca)",
        "Rabat-Salé Airport (Rabat)",
        "Salé",
        "Témara",
        "Skhirat",
        "Harhoura",
        "Souissi (Rabat)",
        "Agdal (Rabat)",
        "Medina (Rabat)",
        "Hassan Tower (Rabat)",
        "Menara (Marrakech)",
        "Gueliz (Marrakech)",
        "Guéliz-Marrakech",
        "Hivernage (Marrakech)",
        "Médina (Marrakech)",
        "La Palmeraie (Marrakech)",
        "Sidi Abdallah Ghiat (Marrakech)",
        "Douar Lahna (Marrakech)",
        "Daoudiate (Marrakech)",
        "Targa (Marrakech)",
        "Al Massira Airport (Agadir)",
        "Agadir Al Amal",
        "Inezgane",
        "Taroudant Province",
        "Tafraout",
        "Tiznit Province",
        "Dcheira El Jihadia",
        "Taghazout",
        "Tamraght",
        "El Menzeh (Tangier)",
        "Marshan (Tangier)",
        "Achakkar (Tangier)",
        "Iberia (Tangier)",
        "M'Nar Park (Tangier)",
        "Beni Makada (Tangier)",
        "Tangier Ibn Battouta Airport (Tangier)",
        "Malabata (Tangier)",
        "Asilah",
        "Chefchaouen Province",
        "Tetouan Province",
        "Oued Laou",
        "Martil",
        "Fnideq",
        "Tetouan-Tanger-Med Port",
        "M'diq",
        "Castillejos",
        "Driouch Province",
        "Targuist",
        "Taounate",
        "Oulad Mimoun",
        "El Hajeb",
        "Ifrane",
        "Azrou",
        "Timahdite",
        "Khemisset",
        "M'rirt",
        "Sidi Slimane Province",
        "Sidi Yahya El Gharb",
        "Khouribga Province",
        "Oued Zem",
        "Oulad Abbou",
        "Ben Ahmed",
        "Bouznika",
        "Khouribga",
        "Bir Jdid",
        "Fquih Ben Salah",
        "Youssoufia",
        "Settat Province",
        "Berrechid",
        "Soualem",
        "Benslimane",
        "Oulad H'Riz Sahel",
        "El Jadida Province",
        "Safi Province",
        "Azemmour",
        "Boujdour Province",
        "Laâyoune Province",
        "Dakhla-Oued Ed-Dahab Province",
        "Marrakech-Menara Airport (Marrakech)",
        "Ouarzazate Province",
        "Skoura",
        "Tinghir Province",
        "Boumalne-Dadès",
        "Aït Benhaddou",
        "Midelt Province",
        "Errachidia Province",
        "Zaouiat Sidi Hamza",
        "Tinghir",
        "Aoufous",
        "Guelmim Province",
        "Assa",
        "Tata Province",
        "Sidi Ifni",
        "Tafraout Province",
        "Ait Melloul",
        "Biougra",
        "Tiznit Province",
        "Tata Province",
        "Taliouine",
        "Taroudant Province",
        "Ait Baha",
        "Ait Iaaza",
        "Agadir-Ida Ou Tanane Province",
        "Dcheira El Jihadia",
        "Inezgane",
        "Agadir Al Amal",
        "Al Hoceima Province",
        "Guercif",
        "Jrada",
        "Midar",
        "Tafoughalt",
        "Taourirt Province",
        "Jebha",
        "Ajdir",
        "Amalou",
        "Bni Bouayach",
        "Oulad Settout",
        "Tissa",
        "Bni Drar",
        "Alnif",
        "Rissani",
        "Zagora Province",
        "Tamegroute",
        "Foum Zguid",
        "M'Hamid El Ghizlane",
        "Tinzouline",
        "Zaouia Sidi Taieb",
        "Ouarzazate Province",
        "Skoura",
        "Aït Benhaddou",
        "Tinghir Province",
        "Tinghir",
        "Boumalne-Dadès",
        "Zaouiat Sidi Hamza",
        "Agdz",
        "Nkob",
        "Guelmim Province",
        "Assa",
        "Tata Province",
        "Sidi Ifni",
        "Tafraout Province",
        "Ait Melloul",
        "Biougra",
        "Tiznit Province",
        "Tata Province",
        "Taliouine",
        "Taroudant Province",
        "Ait Baha",
        "Ait Iaaza",
        "Agadir-Ida Ou Tanane Province",
        "Dcheira El Jihadia",
        "Inezgane",
        "Agadir Al Amal"
    ];

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // Get a random Moroccan city from the list
        $cityName = $this->faker->randomElement($this->moroccanCities);

        return [
            'name' => $cityName,
        ];
    }
}
